title:            Ferdhika Yudira
description:      A handsome man created simple web.
url:              ferdhika31.github.io
signoff:          Ferdhika Yudira
disqus_shortname: ferdhikablog
facebook_appid:   136269433249394
google_analytics: UA-42800486-1
emoji_dir:        /images/emoji

links:
  - name:         About
    url:          /about
  - name:         Blog
    url:          /
  - name:         Email
    url:          mailto:rpl4rt08@gmail.com
    external:     true
  - name:         Twitter
    url:          http://twitter.com/ferdhikaaa
    external:     true
  - name:         Facebook
    url:          http://facebook.com/ferdhika31
    external:     true
  - name:         RSS
    url:          /feed.xml
pygments:         true
permalink:        date
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
